---
- name: check if staging directory exists or create it
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: check if wp install directory exists or create it
  file:
    path: "{{ wp_install_dir }}"
    state: directory
    mode: 0755

- name: download wordpress
  get_url:
    dest: "{{ tmp_dir }}/latest.tar.gz"
    url: "https://wordpress.org/latest.tar.gz"

- name: untar wordpress
  unarchive:
    copy: no
    src: "{{ tmp_dir }}/latest.tar.gz"
    dest: "{{ wp_install_dir }}"
    owner: root
    group: apache

- name: install mysqldb python module
  yum:
    name: MySQL-python
    state: present

- name: create the wordpress database
  mysql_db: 
    name: "{{ wordpress_db }}"
    state: present

- name: generate the database password
  command: openssl rand -base64 33
  register: wp_db_pass
  changed_when: no

- name: create the database user
  mysql_user:
    name: "{{ wordpress_user }}"
    password: "{{ wp_db_pass.stdout }}"
    priv: "{{ wordpress_db }}.*:ALL"
    state: present

- name: download salts
  get_url:
    url: "https://api.wordpress.org/secret-key/1.1/salt/"
    dest: "{{ tmp_dir }}/salts"
    force: yes

- name: get the salts
  command: "cat {{ tmp_dir }}/salts"
  register: salts

- name: render and copy wp-config 
  template:
    src: wp-config.php.j2
    dest: "{{ wp_install_dir }}/wordpress/wp-config.php"
    mode: 0644
